# Generated by Django 4.1.4 on 2022-12-23 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True, max_length=256)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('website', models.URLField(unique=True)),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=64)),
                ('open_hour', models.TimeField()),
                ('close_hour', models.TimeField()),
                ('open_hour_weekend', models.TimeField()),
                ('close_hour_weekend', models.TimeField()),
                ('open_on_sunday', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Name', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+111111', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.DurationField()),
                ('description', models.TextField(blank=True, max_length=256)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='eventcalendar.business')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=128, unique=True)),
                ('suppliers', models.ManyToManyField(related_name='customers', to='eventcalendar.business')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(max_length=64)),
                ('service_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer_phone', models.CharField(max_length=13)),
                ('customer_name', models.CharField(max_length=64)),
                ('day', models.DateField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('duration', models.DurationField()),
                ('status', models.IntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='eventcalendar.business')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='eventcalendar.customer')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='eventcalendar.service')),
            ],
        ),
    ]
