# Generated by Django 4.1.4 on 2022-12-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0002_business_user_name_user_phone_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_name',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
