# Generated by Django 4.1.4 on 2022-12-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0003_alter_appointment_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service_name',
            field=models.CharField(max_length=64),
        ),
    ]
