# Generated by Django 4.1.4 on 2022-12-24 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0006_alter_appointment_end_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
    ]
