# Generated by Django 4.1.4 on 2022-12-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0008_alter_appointment_end_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
