# Generated by Django 4.1.4 on 2022-12-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0009_alter_appointment_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=128, unique=True),
        ),
    ]
