# Generated by Django 4.1.4 on 2022-12-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0012_remove_customer_email_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
