# Generated by Django 4.1.4 on 2022-12-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0013_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
