# Generated by Django 4.1.4 on 2022-12-27 22:52

from django.db import migrations, models
import eventcalendar.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0015_business_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=14, validators=[eventcalendar.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(max_length=14, unique=True, validators=[eventcalendar.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=14, unique=True, validators=[eventcalendar.models.validate_phone]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14, unique=True, validators=[eventcalendar.models.validate_phone]),
        ),
    ]
