# Generated by Django 4.1.4 on 2022-12-28 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0018_alter_appointment_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=128, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='business',
            name='postal_code',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=128, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
