# Generated by Django 4.1.4 on 2022-12-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcalendar', '0019_alter_business_email_alter_business_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='brand_name',
            field=models.CharField(default=models.CharField(max_length=64, unique=True), max_length=64),
        ),
    ]
